config/routes.rb
Rails.application.routes.draw do
  resources :audit_logs, except: [:new, :edit, :destroy] do
    member do
      get :confirmed
    end
  end
  namespace :admin do
      resources :users
      resources :posts
      resources :admin_users

      root to: "users#index"
    end
  resources :posts do
    member do
      get :approved
    end
  end
  devise_for :users, skip: [:registrations]
  root to: 'pages#home'
end

app/models/admin_user.rb
class AdminUser < User

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/audit_log.rb
class AuditLog < ApplicationRecord
  belongs_to :user
  validates_presence_of :user_id, :status, :start_date
  enum status: { pending: 0, confirmed: 1 }

  after_initialize :set_defaults

  private

    def set_defaults
      self.start_date ||= Date.today - 6.days
    end
end

app/models/employee.rb
class Employee < User

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates_presence_of :date, :rationale, :overtime_request
  validates :overtime_request, numericality: { greater_than: 0.0 }
  enum status: { submitted: 0, approved: 1, rejected: 2 }
  after_save :update_audit_log

  def self.posts_by(user)
    order(created_at: :desc).where(user: user)
  end

  private

    def update_audit_log
      audit_log = AuditLog.where(user_id: self.user_id, start_date: (self.date - 7.days..self.date)).last
      if audit_log
        audit_log.confirmed!
      end
    end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :audit_logs
  validates_presence_of :first_name, :last_name, :phone

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  REGEX_PHONE = /\A[0-9]*\Z/

  validates_format_of :phone, with: REGEX_PHONE

  validates :phone, length: { is: 9 }

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/admin/admin_users_controller.rb
module Admin
  class AdminUsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = AdminUser.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   AdminUser.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin

  def self.admin_users
    ['AdminUser']
  end

  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_user!
    before_action :authenticate_admin

    def authenticate_admin
      unless Admin.admin_users.include?(current_user.try(:type))
        redirect_to root_path, notice: "You have no access to this area"
      end
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Post.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Post.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def admin_types
    ['AdminUser']
  end
  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to root_path
  end

end

app/controllers/audit_logs_controller.rb
class AuditLogsController < ApplicationController
  def index
    @audit_logs = AuditLog.all.page(params[:page]).per(10)
    authorize @audit_logs
  end

  def confirmed
    audit_log = AuditLog.find(params[:id])
    if audit_log.confirmed!
      audit_log.update!(end_date: Date.today)
      redirect_to root_path, notice: "You have confirmed your audit log"
    else
      redirect_to root_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    if admin_types.include?(current_user.type)
      @pending_approvals = Post.submitted
      @recent_audit = AuditLog.last(10)
    else
      @pending_audit_logs = current_user.audit_logs.pending
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :approved]

  def index
    @posts = Post.posts_by(current_user).page(params[:page]).per(10)
  end

  def show
  end

  def approved
    authorize @post
    if @post.approved!
      redirect_to root_path, notice: "The post has been successfully approved"
    end
  end


  def new
    @post = Post.new
  end

  def edit
    authorize @post
  end

  def create
    @post = Post.create(post_params)
    @post.user = current_user
    if @post.save
      redirect_to @post, notice: "Your post was successfully created"
    else
      render :new
    end
  end

  def update
    authorize @post
    if @post.update(post_params)
      redirect_to @post, notice: "Your post was successfully updated"
    else
      render :edit, notice: "Something went wrong, please check if filled the information correctly"
    end
  end

  def destroy
    if @post.delete
      redirect_to posts_path, notice: "Post was successfully deleted"
    end
  end

  private

  def post_params
    params.require(:post).permit(:date, :rationale, :status, :overtime_request)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


  def admin_types
    ['AdminUser']
  end

  def active?(path)
    "active" if current_page(path)
  end

    def status_label(status)
    status_span_generator(status)
  end

  private

  def status_span_generator(status)
    case status
    when 'submitted'
      content_tag(:span, status.titleize, class: "badge badge-primary")
    when 'approved'
      content_tag(:span, status.titleize, class: "badge badge-success")
    when 'rejected'
      content_tag(:span, status.titleize, class: "badge badge-danger")
    when 'pending'
      content_tag(:span, status.titleize, class: "badge badge-warning")
    when 'confirmed'
      content_tag(:span, status.titleize, class: "badge badge-success")
    end
  end
end

app/helpers/audit_logs_helper.rb
module AuditLogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def confirmation_date(audit)
    audit.end_date ?  audit.end_date.strftime("%d/%m/%Y") : 'Waiting to be confirmed'
  end

  def start_date(audit)
    audit.start_date.strftime("%d/%m/%Y")
  end
end

app/helpers/posts_helper.rb
module PostsHelper

end

app/views/audit_logs/_audit_log.html.erb
<tr>
  <th scope="row"> <%= audit_log.id %></th>
  <td> <%= audit_log.user.full_name %></td>
  <td> <%= audit_log.start_date  %></td>
  <td> <%= audit_log.end_date %></td>
  <td> <%= status_label(audit_log.status) %></td>
  <td> <%=  %></td>
  <td> <%= %></td>
  <td> <%=  %></td>
</tr>

app/views/audit_logs/index.html.erb
<br>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Employee</th>
      <th scope="col">Week Starting</th>
      <th scope="col">Confirmed </th>
      <th scope="col">Status</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <%= render @audit_logs %>
  </tbody>
</table>
<br>
<%= paginate @audit_logs %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OvertimeApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">

      <%= render 'shared/nav' %>

      <%= yield %>

    </div>
    <%= render 'shared/alerts' %>
  </body>
</html>

app/views/pages/_admin.html.erb
<div class="container">
  <h2 class="text-center" >Items pending of approval</h2>
  <hr>
  <div class="pending-overtime-approvals row">
    <%= render partial: 'pending_approval', locals: { pending_approvals: @pending_approvals }  %>
  </div>
   <h2 class="text-center" >Confirmation Log</h2>
  <hr>
  <div class="pending-overtime-approvals row">
    <%= render partial: 'confirmation', locals: { recent_audit: @recent_audit }  %>
  </div>
  <div>
  <%= link_to  "See All Logs", audit_logs_path, class: 'btn btn-outline-success btn-block' %>
  </div>
  <br>
</div>

app/views/pages/_confirmation.html.erb
<% recent_audit.each do |audit| %>
<div class="homepage-block col-xs-12 col-sm-6 col-md-3">
  <h6>
    <%= audit.user.full_name %>
  </h6>
  <p>
    <span class="pending-details"> Week starting: </span><%= start_date(audit) %>
  </p>
    <p>
    <span class="pending-details"> Confirmed at: </span><%= confirmation_date(audit) %>
  </p>
  <p>
    <span class="pending-details"> Status: </span><%= status_label(audit.status) %>
  </p>
</div>
<% end %>

app/views/pages/_employee.html.erb
<div class="container">
  <div class="row">
    <% if @pending_audit_logs.count > 0 %>
    <div class="col-md-12 pending-overtime-approvals employee-blocks">
      <h3 class="text-center">Pending your confirmation</h3>
      <%= render partial: "pending_audit_logs", locals: { pending_audit_logs: @pending_audit_logs} %>
    </div>
    <% end %>
    <div class="col-md-12 pending-overtime-approvals employee-blocks ">
      <%= link_to  "Request overtime approval", new_post_path, class: "btn btn-block btn-outline-primary" %>
    </div>
  </div>
</div>

app/views/pages/_pending_approval.html.erb
<% pending_approvals.each do |post| %>
  <div class="homepage-block col-xs-12 col-sm-6 col-md-3">
    <h6>
      <%= post.user.full_name %>
    </h6>
    <p>
      <span class="pending-details"> Date submitted: </span><%= post.date %>
    </p>
      <p>
      <span class="pending-details"> Rationale: </span><%= truncate post.rationale %>
    </p>
    <div class="row">
      <div class="col-md-6 column">
        <%= link_to 'Approve', approved_post_path(post), class: 'btn btn-sm btn-success btn-block', id: "approved_#{post.id}" %>
      </div>
      <div class="col-md-6 column">
        <%= link_to 'Review', edit_post_path(post), class: 'btn btn-sm btn-warning btn-block' %>
      </div>
    </div>
  </div>
<% end %>

app/views/pages/_pending_audit_logs.html.erb
<% pending_audit_logs.each do |audit|  %>
  <%= link_to  "I confirm that I did not perform any overtime for the week: #{start_date(audit)}", confirmed_audit_log_path(audit), class: "btn btn-warning btn-block", data: {  confirm: 'Are you sure? This will confirm you have not perform overtime'}, id: "confirmed_#{audit.id}" %>
<% end %>

app/views/pages/home.html.erb
<% if admin_types.include?(current_user.try(:type)) %>
  <%= render  "admin" %>
<% else %>
  <%= render  "employee" %>
<% end %>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>

  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <%= js add_gritter(msg, :image => :notice, :title => "Overtime App", :time => 3000) %>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :date %>
    <%= f.date_field :date, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :rationale %>
    <%= f.text_field :rationale, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :overtime_request %>
    <%= f.number_field :overtime_request, class: "form-control", step: :any %>
  </div>

  <%= render partial: "status", locals: { f: f } if current_user.type == "AdminUser" %>

  <div class="form-group">
    <%= f.submit 'Save', class: "btn btn-outline-primary btn-block" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<tr>
  <th scope="row"> <%= post.id %></th>
  <td> <%= post.date %></td>
  <td> <%= post.user.full_name %></td>
  <td> <%= link_to truncate(post.rationale), post_path(post) %></td>
  <td> <%= post.overtime_request.to_f %></td>
  <td> <%= status_label(post.status) %></td>
  <td> <%= link_to fa_icon('edit'), edit_post_path(post), id: "edit_#{post.id}" if policy(post).update? %></td>
  <td> <%= link_to fa_icon('trash'), post_path(post), id: "delete_#{post.id}", method: :delete, data: {confirm: "Are you sure?"} %></td>
</tr>

app/views/posts/_status.html.erb
<div class="form-group">
    <%= f.radio_button :status, 'submitted' %>
    <%= f.label :status, "Submitted" %>
    <%= f.radio_button :status, 'approved' %>
    <%= f.label :status, "Approved" %>
    <%= f.radio_button :status, 'rejected' %>
    <%= f.label :status, "Rejected" %>
  </div>

app/views/posts/edit.html.erb
<div class="card w-50">
  <div class="card-body">
    <h5 class="card-title">Edit</h5>
    <%= render 'form' %>
  </div>
</div>

app/views/posts/index.html.erb
<br>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Date</th>
      <th scope="col">User</th>
      <th scope="col">Rationale</th>
      <th scope="col">Overtime requested</th>
      <th scope="col">Status</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <%= render @posts %>
  </tbody>
</table>
<br>
<%= paginate @posts %>

app/views/posts/new.html.erb
<h3>New Post</h3>
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="card">
  <h5 class="card-header"><%= @post.user.first_name %></h5>
  <div class="card-body">
    <h5 class="card-title"><%= @post.rationale %> </h5>
    <p class="card-text"> <%= @post.date.to_formatted_s(:long_ordinal) %> </p>
    <p class="card-text"> <%= @post.overtime_request.to_f %> hours requested </p>
    <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-outline-primary" if policy(@post).update? %>
  </div>
</div>

app/views/shared/_alerts.html.erb
<% if flash[:notice] %>
  <%= js add_gritter(flash[:notice], :image => :notice, :title => "Overtime App Notification", :time => 2000) %>
<% elsif flash[:error] %>
  <%= js add_gritter(flash[:error], :image => :error, :title => "Overtime App Error", :time => 3000) %>
<% else %>
  <%= js add_gritter(flash[:alert], :image => :warning, :title => "Overtime App Alert", :time => 3000) %>
<% end %>

app/views/shared/_jumbotron.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Fluid jumbotron</h1>
    <p class="lead">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="logo">
  <h3>Time Tracker</h3>
</div>
<nav class="navbar navbar-expand-lg navbar-light bg-light custom-nav">
  <a class="navbar-brand" href="/">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <% if current_user %>
        <li class="nav-item">
          <%= link_to 'Time Entries', posts_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to 'Request overtime', new_post_path, class: "nav-link", id: "new_post_from_nav" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Admin Dashboard', admin_root_path, class: "nav-link" if admin_types.include?(current_user.try(:type)) %>
        </li>
        <li class="nav-item">
          <%= link_to 'Audit Logs', audit_logs_path, class: "nav-link" if policy(AuditLog).index? %>
        </li>
        <li class="nav-item">
        <%= link_to 'Logout', destroy_user_session_path, class: "nav-link", method: :delete %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Login',new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>